export type Platform = "Kleinanzeigen" | "Immowelt" | "WG-Gesucht" | "ImmoScout24";
export type ListingStatus = "neu" | "interessant" | "abgelehnt" | "vorbereitet" | "versendet";

export interface Listing {
  id: string;
  title: string;
  rentWarm: number;
  rooms: number;
  sizeSqm: number;
  city: string;
  platform: Platform;
  status: ListingStatus;
  url: string;
}

export const STATUS_LABELS: Record<ListingStatus, string> = {
  neu: "Neu",
  interessant: "Interessant",
  abgelehnt: "Abgelehnt",
  vorbereitet: "Anfrage vorbereitet",
  versendet: "Versendet",
};

export const initialListings: Listing[] = [
  {
    id: "l01",
    title: "Helle 2-Zimmer-Wohnung nahe Hauptbahnhof",
    rentWarm: 690,
    rooms: 2,
    sizeSqm: 58,
    city: "Mönchengladbach",
    platform: "ImmoScout24",
    status: "neu",
    url: "https://www.immobilienscout24.de/expose/beispiel-1",
  },
  {
    id: "l02",
    title: "Ruhige 2-Zimmer-Wohnung mit Balkon",
    rentWarm: 715,
    rooms: 2,
    sizeSqm: 61,
    city: "Kaarst",
    platform: "Immowelt",
    status: "interessant",
    url: "https://www.immowelt.de/expose/beispiel-2",
  },
  {
    id: "l03",
    title: "2 Zimmer, EBK, Tageslichtbad",
    rentWarm: 670,
    rooms: 2,
    sizeSqm: 54,
    city: "Mönchengladbach",
    platform: "Kleinanzeigen",
    status: "neu",
    url: "https://www.kleinanzeigen.de/s-anzeige/beispiel-3",
  },
  {
    id: "l04",
    title: "Modernisierte 2-Zimmer-Wohnung, Nähe Innenstadt",
    rentWarm: 730,
    rooms: 2,
    sizeSqm: 63,
    city: "Mönchengladbach",
    platform: "ImmoScout24",
    status: "vorbereitet",
    url: "https://www.immobilienscout24.de/expose/beispiel-4",
  },
  {
    id: "l05",
    title: "2-Zimmer-Wohnung mit kleinem Garten",
    rentWarm: 705,
    rooms: 2,
    sizeSqm: 59,
    city: "Kaarst",
    platform: "WG-Gesucht",
    status: "neu",
    url: "https://www.wg-gesucht.de/beispiel-5",
  },
  {
    id: "l06",
    title: "Kompakte 2-Zimmer-Wohnung, gut angebunden",
    rentWarm: 655,
    rooms: 2,
    sizeSqm: 49,
    city: "Mönchengladbach",
    platform: "Kleinanzeigen",
    status: "abgelehnt",
    url: "https://www.kleinanzeigen.de/s-anzeige/beispiel-6",
  },
  {
    id: "l07",
    title: "2-Zimmer-Wohnung mit Wannenbad und Stellplatz",
    rentWarm: 745,
    rooms: 2,
    sizeSqm: 65,
    city: "Kaarst",
    platform: "Immowelt",
    status: "neu",
    url: "https://www.immowelt.de/expose/beispiel-7",
  },
  {
    id: "l08",
    title: "Altbau-Charme, 2 Zimmer, hohe Decken",
    rentWarm: 680,
    rooms: 2,
    sizeSqm: 56,
    city: "Mönchengladbach",
    platform: "WG-Gesucht",
    status: "interessant",
    url: "https://www.wg-gesucht.de/beispiel-8",
  },
  {
    id: "l09",
    title: "2-Zimmer-Neubauwohnung mit Fußbodenheizung",
    rentWarm: 750,
    rooms: 2,
    sizeSqm: 62,
    city: "Kaarst",
    platform: "ImmoScout24",
    status: "neu",
    url: "https://www.immobilienscout24.de/expose/beispiel-9",
  },
  {
    id: "l10",
    title: "Zentrale 2-Zimmer-Wohnung, ruhige Lage im Hof",
    rentWarm: 660,
    rooms: 2,
    sizeSqm: 52,
    city: "Mönchengladbach",
    platform: "Kleinanzeigen",
    status: "neu",
    url: "https://www.kleinanzeigen.de/s-anzeige/beispiel-10",
  },
  {
    id: "l11",
    title: "2-Zimmer-Wohnung, Küche einbaufertig",
    rentWarm: 695,
    rooms: 2,
    sizeSqm: 57,
    city: "Mönchengladbach",
    platform: "Immowelt",
    status: "versendet",
    url: "https://www.immowelt.de/expose/beispiel-11",
  },
  {
    id: "l12",
    title: "2-Zimmer-Wohnung mit Balkon Richtung Park",
    rentWarm: 720,
    rooms: 2,
    sizeSqm: 60,
    city: "Kaarst",
    platform: "WG-Gesucht",
    status: "neu",
    url: "https://www.wg-gesucht.de/beispiel-12",
  },
  {
    id: "l13",
    title: "Frisch renovierte 2-Zimmer-Wohnung",
    rentWarm: 700,
    rooms: 2,
    sizeSqm: 58,
    city: "Mönchengladbach",
    platform: "ImmoScout24",
    status: "interessant",
    url: "https://www.immobilienscout24.de/expose/beispiel-13",
  },
  {
    id: "l14",
    title: "2-Zimmer-Wohnung mit Loggia",
    rentWarm: 675,
    rooms: 2,
    sizeSqm: 55,
    city: "Kaarst",
    platform: "Kleinanzeigen",
    status: "neu",
    url: "https://www.kleinanzeigen.de/s-anzeige/beispiel-14",
  },
  {
    id: "l15",
    title: "2-Zimmer-Wohnung, Nähe Bahnhof Rheydt",
    rentWarm: 640,
    rooms: 2,
    sizeSqm: 48,
    city: "Mönchengladbach",
    platform: "Immowelt",
    status: "abgelehnt",
    url: "https://www.immowelt.de/expose/beispiel-15",
  },
  {
    id: "l16",
    title: "2-Zimmer-Wohnung mit Einbauküche und Keller",
    rentWarm: 710,
    rooms: 2,
    sizeSqm: 60,
    city: "Mönchengladbach",
    platform: "WG-Gesucht",
    status: "neu",
    url: "https://www.wg-gesucht.de/beispiel-16",
  },
  {
    id: "l17",
    title: "2-Zimmer-Wohnung mit Terrasse",
    rentWarm: 735,
    rooms: 2,
    sizeSqm: 64,
    city: "Kaarst",
    platform: "ImmoScout24",
    status: "neu",
    url: "https://www.immobilienscout24.de/expose/beispiel-17",
  },
  {
    id: "l18",
    title: "2-Zimmer-Wohnung, gepflegtes Mehrfamilienhaus",
    rentWarm: 665,
    rooms: 2,
    sizeSqm: 53,
    city: "Mönchengladbach",
    platform: "Kleinanzeigen",
    status: "vorbereitet",
    url: "https://www.kleinanzeigen.de/s-anzeige/beispiel-18",
  },
];
